language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
bundler_args: --without development production
before_install:
  - gem update bundler
  - sed -i -e "/ruby '1.9.3'/d" Gemfile
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:schema:load --quiet
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    - ogataken@gmail.com
script: bundle exec rspec -fd
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: 2.0.0
